-- MySQL Script generated by MySQL Workbench
-- Ter 22 Mar 2016 18:47:33 BRT
-- Model: SCE Datase Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sce` ;

-- -----------------------------------------------------
-- Table `sce`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `razao_social` VARCHAR(100) NULL COMMENT '',
  `cnpj` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `telefone` INT(11) NULL COMMENT '',
  `telefone_2` INT(11) NULL COMMENT '',
  `endereco_rua` VARCHAR(45) NULL COMMENT '',
  `endereco_numero` VARCHAR(45) NULL COMMENT '',
  `endereco_bairro` VARCHAR(45) NULL COMMENT '',
  `endereco_cep` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_empresa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce`.`turma` (
  `id_turma` VARCHAR(45) NOT NULL COMMENT '',
  `turno` VARCHAR(45) NOT NULL COMMENT '',
  `curso` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id_turma`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce`.`orientador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce`.`orientador` (
  `siap` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`siap`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce`.`estagiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce`.`estagiario` (
  `matricula` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `periodo_inicio` DATE NOT NULL COMMENT '',
  `periodo_fim` DATE NOT NULL COMMENT '',
  `empresa` VARCHAR(45) NOT NULL COMMENT '',
  `foto` VARCHAR(256) NULL COMMENT '',
  `observacao` VARCHAR(4096) NULL COMMENT '',
  `empresa_id_empresa` INT NOT NULL COMMENT '',
  `turma_id_turma` VARCHAR(45) NOT NULL COMMENT '',
  `orientador_siap` INT NOT NULL COMMENT '',
  PRIMARY KEY (`matricula`)  COMMENT '',
  INDEX `fk_estagiario_empresa` (`empresa_id_empresa` ASC)  COMMENT '',
  INDEX `fk_estagiario_turma` (`turma_id_turma` ASC)  COMMENT '',
  INDEX `fk_estagiario_orientador` (`orientador_siap` ASC)  COMMENT '',
  CONSTRAINT `fk_estagiario_empresa`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `sce`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estagiario_turma`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `sce`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estagiario_orientador`
    FOREIGN KEY (`orientador_siap`)
    REFERENCES `sce`.`orientador` (`siap`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce`.`usuario` (
  `usuario` VARCHAR(20) NOT NULL COMMENT '',
  `senha` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`usuario`)  COMMENT '')
ENGINE = InnoDB;

CREATE USER 'sce' IDENTIFIED BY 'sce_password';

GRANT ALL ON `sce`.* TO 'sce';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
